import type { MessageSchema } from "./zh-CN";

const enUS = {
  common: {
    close: "Close", cancel: "Cancel", save: "Save", delete: "Delete", configure: "Configure", open: "Open", clear: "Clear", optional: "Optional", required: "Required", expand: "Expand", collapse: "Collapse", uploadImage: "Upload image", replaceImage: "Replace image", removeAvatar: "Remove avatar", providerIconAlt: "{name} icon", selectedProviderAvatarAlt: "Selected provider avatar",
  },
  navigation: { main: "Main navigation", dashboard: "Dashboard", providers: "Providers", settings: "Settings" },
  dashboard: {
    title: "Dashboard", searchPlaceholder: "Search providers or key notes", addConfiguration: "Add configuration", statisticsLabel: "Key statistics", providerCount: "Providers", keyCount: "Total keys", availableKeyCount: "Available keys", dragToReorder: "Drag to reorder", officialProvider: "Official", customProvider: "Custom", noPlatformUrl: "No management URL configured", availableSummary: "({count} available)", refreshStatus: "Check status again", validationUnsupported: "Key checking is not configured for this provider", lastChecked: "Last checked: {time}", addKey: "Add key",
    columns: { remark: "Note", maskedKey: "API Key (partially hidden)", status: "Status", actions: "Actions" },
    actions: { checkKey: "Check key", editKey: "Edit key", copyKey: "Copy key", copied: "Copied", deleteKey: "Delete key" },
    keyDisclosure: "Only part of each key is shown. Full secrets are never returned to the list.",
    empty: { noMatchesTitle: "No matching provider or note found", noProvidersTitle: "No providers configured yet", noMatchesDescription: "Try a different search term.", noProvidersDescription: "Start with a built-in provider or create a custom one.", clearSearch: "Clear search" },
    deleteKeyDialog: { title: "Delete API key", message: "Delete this API key? This action cannot be undone." },
    notices: { copied: "Copied to clipboard", copyFailed: "Copy failed", checkingProvider: "Checking every key for this provider...", checkComplete: "Check complete: {valid} available, {invalid} invalid, {error} errors, {unsupported} unsupported", checkFailed: "Check failed. Verify the network and provider configuration.", validationUnsupported: "Configure a check method before checking this provider", keyValid: "This API key is valid", keyInvalid: "This API key is invalid", keyCheckError: "The check failed. Try again later.", keyReplaced: "API key replaced", remarkSaved: "Note saved", keySaved: "API key saved", editSaveFailed: "Could not save changes", keySaveFailed: "Could not save API key", keyDeleted: "API key deleted", keyDeleteFailed: "Could not delete API key", openPlatformFailed: "Could not open the provider management page", providerConfigured: "This provider is already configured", providerAdded: "Provider configuration added", providerExists: "A provider with this name already exists", customProviderAdded: "Custom provider configuration added" },
  },
  providers: {
    title: "Providers", description: "Manage built-in services and custom API endpoints.", addProvider: "Add provider", builtin: "Built-in provider", custom: "Custom provider", keyCount: "{count} key | {count} keys", deleteAction: "Delete provider", deleteAria: "Delete {name}",
    deleteDialog: { title: "Delete provider", withKeys: "Delete “{name}”? Its {count} API key will also be deleted. This action cannot be undone. | Delete “{name}”? Its {count} API keys will also be deleted. This action cannot be undone.", withoutKeys: "Delete “{name}”? This action cannot be undone." },
    notices: { addFailed: "Could not add provider: the name already exists", added: "Custom provider added and shown on the dashboard", saveFailed: "Could not save: the provider name exists or the configuration is invalid", saved: "Provider configuration saved and synced to the dashboard", deleted: "Deleted provider “{name}”", deleteFailed: "Could not delete provider" },
  },
  settings: {
    title: "Settings", description: "Appearance, language, local data, and application information.",
    language: { title: "Language", description: "Choose the interface language. System default is selected initially.", label: "Interface language", system: "System default", simplifiedChinese: "简体中文", traditionalChinese: "繁體中文", english: "English", japanese: "日本語" },
    appearance: { title: "Appearance", description: "Choose the interface color theme. System default responds automatically to appearance changes.", label: "Color theme", system: "System default", light: "Light", dark: "Dark" },
    storage: { title: "Local storage", description: "Provider and key metadata is stored here, and application settings are written to settings.json.", loading: "Reading the local data directory", openFailed: "Could not open the local storage location" },
    logs: { title: "Application logs", description: "Local operations and key-check results", loading: "Reading the log directory", clearLogs: "Clear logs", openDirectory: "Open folder", cleared: "Logs cleared", clearFailed: "Could not clear logs", openFailed: "Could not open the log directory", clearDialogTitle: "Clear application logs", clearDialogMessage: "Clear all local application logs? This action cannot be undone." },
    version: { current: "Current version {version}", checkUpdates: "Check for updates", latest: "You are using the latest version", checkFailed: "Could not check for updates. Try again later.", githubFailed: "Could not open the GitHub repository", releaseFailed: "Could not open the release download page" },
  },
  keyDialog: { unnamed: "Unnamed key", addTitle: "Add API key", editTitle: "Edit API key", remark: "Note", remarkPlaceholder: "For example: Development", key: "API Key", newKey: "New API Key", keyPlaceholder: "Paste API key", saveKey: "Save key", saveChanges: "Save changes", errors: { keyRequired: "Enter an API key", noChanges: "Change the note or enter a new API key" } },
  providerDialog: {
    configurationTitle: "Add configuration", configurationDescription: "Choose a built-in provider or configure a custom one.", configurationType: "Configuration type", builtinTab: "Built-in provider", customTab: "Custom provider", configured: "Configured", avatar: "Provider avatar", avatarHelp: "PNG, JPG, or WebP, up to 2 MB", avatarHelpOptional: "Optional. PNG, JPG, or WebP, up to 2 MB.", name: "Provider name", namePlaceholder: "For example: Internal model gateway / OneAPI", platformUrl: "Management URL", addConfiguration: "Add configuration", addProvider: "Add provider", customTitle: "Add custom provider", customDescription: "Configure the provider name, endpoint, and optional avatar.", editTitle: "Provider configuration", editDescription: "Change the provider name, management URL, and key-check method.",
    validation: { title: "Key checking", mode: "Check method", none: "Do not check", openaiCompatible: "OpenAI-compatible API", bearer: "Bearer token", apiKeyHeader: "API key header", baseUrl: "API base URL", endpoint: "Check endpoint", headerName: "Key header name", noneHelp: "API keys will not be sent to any external address.", securityWarning: "The full API key will be sent to the configured HTTPS address when checked.", hostWarning: "The full API key will be sent to {host} when checked." },
    errors: { selectBuiltin: "Select a built-in provider", nameRequired: "Enter a provider name", platformUrlRequired: "Enter a management URL", invalidUrl: "Enter a valid HTTP or HTTPS URL", validationUrlRequired: "Enter a valid check URL", validationHttpsRequired: "The check URL must use HTTPS", validationUrlUnsafe: "The check URL cannot contain credentials, query parameters, or a local network address", validationHeaderRequired: "Enter the key header name", validationHeaderInvalid: "This header name is invalid or not allowed", invalidAvatarType: "The avatar must be a PNG, JPG, or WebP image", avatarTooLarge: "The avatar must not exceed 2 MB", avatarReadFailed: "Could not read the avatar. Choose the image again." },
  },
  status: { valid: "Available", untested: "Not checked", invalid: "Invalid", unsupported: "Checking unsupported", error: "Check error", checking: "Checking" },
  statusReasons: { timeout: "The check request timed out", network: "Could not connect to the check endpoint", rateLimited: "The provider rate-limited the check", serverUnavailable: "The provider service is temporarily unavailable", endpointInvalid: "The check endpoint is invalid or redirected", unexpectedStatus: "The provider returned an unrecognized status" },
  update: { stable: "Stable", available: "New version v{version} available", current: "Current version v{version}", view: "View update", remindLater: "Remind me later", later: "Later", downloadAndInstall: "Download and install", downloading: "Downloading update", timeout: "Download timed out. Check your network and try again.", failed: "Update download failed. Try again later." },
  errors: { desktopRequired: "Local data features are only available in the desktop app", dataDirectoryUnavailable: "Could not read the application data directory", logDirectoryUnavailable: "Could not read the log directory", directoryCreateFailed: "Could not create a required directory", directoryOpenFailed: "Could not open the directory", dataReadFailed: "Could not read local data", dataInvalid: "The local data format is invalid", dataSaveFailed: "Could not save local data", keyringUnavailable: "The system credential store is unavailable", keyringReadFailed: "Could not read the API key from the system credential store", keyringWriteFailed: "Could not write to the system credential store", keyringDeleteFailed: "Could not delete the API key from the system credential store", networkClientFailed: "Could not initialize the network connection", versionInvalid: "The application version is invalid", updateCheckFailed: "Could not connect to the update service", updateResponseTooLarge: "The update service response is too large", updateDataInvalid: "The update information is invalid", updateTagInvalid: "The update version tag is invalid", updateManifestFailed: "Could not read the signed update manifest", updateDownloadTimeout: "The update download timed out. Check your network and try again.", updateDownloadFailed: "The update download or signature verification failed", updateInstallFailed: "Could not install the update", updateNotAvailable: "No installable update is available for this version", providerNameRequired: "Provider name is required", providerExists: "The provider already exists", providerNameExists: "A provider with this name already exists", providerNotFound: "Provider not found", providerOrderInvalid: "Provider ordering data is incomplete", providerValidationInvalid: "The provider key-check configuration is invalid", apiKeyRequired: "API key is required", apiKeyNotFound: "API key not found", clipboardWriteFailed: "Could not write to the clipboard", settingsReadFailed: "Could not read application settings", settingsInvalid: "The application settings file is invalid", settingsSaveFailed: "Could not save application settings", logUnavailable: "Logging is temporarily unavailable", logClearFailed: "Could not clear the logs", unknown: "The operation failed. Try again later." },
} satisfies MessageSchema;

export default enUS;
