import type { MessageSchema } from "./zh-CN";

const jaJP = {
  common: { close: "閉じる", cancel: "キャンセル", save: "保存", delete: "削除", configure: "設定", open: "開く", clear: "消去", optional: "任意", required: "必須", expand: "展開", collapse: "折りたたむ", uploadImage: "画像をアップロード", replaceImage: "画像を変更", removeAvatar: "アバターを削除", providerIconAlt: "{name} のアイコン", selectedProviderAvatarAlt: "選択したプロバイダーのアバター" },
  navigation: { main: "メインナビゲーション", dashboard: "ホーム", providers: "プロバイダー", settings: "設定" },
  dashboard: {
    title: "ダッシュボード", searchPlaceholder: "プロバイダーまたはキーのメモを検索", addConfiguration: "設定を追加", statisticsLabel: "キーの統計", providerCount: "プロバイダー数", keyCount: "キーの総数", availableKeyCount: "利用可能なキー", dragToReorder: "ドラッグして並べ替え", officialProvider: "公式", customProvider: "カスタム", noPlatformUrl: "管理 URL が設定されていません", availableSummary: "（利用可能: {count}）", refreshStatus: "ステータスを再確認", addKey: "キーを追加",
    columns: { remark: "メモ", maskedKey: "API Key（一部非表示）", status: "ステータス", actions: "操作" },
    actions: { checkKey: "キーを確認", editKey: "キーを編集", copyKey: "キーをコピー", copied: "コピー済み", deleteKey: "キーを削除" },
    keyDisclosure: "キーの一部のみを表示します。完全なシークレットが一覧に返されることはありません。",
    empty: { noMatchesTitle: "一致するプロバイダーまたはメモがありません", noProvidersTitle: "プロバイダーがまだ設定されていません", noMatchesDescription: "別のキーワードで検索してください。", noProvidersDescription: "組み込みプロバイダーを選ぶか、カスタムプロバイダーを作成してください。", clearSearch: "検索をクリア" },
    deleteKeyDialog: { title: "API Key を削除", message: "この API Key を削除しますか？この操作は元に戻せません。" },
    notices: { copied: "クリップボードにコピーしました", copyFailed: "コピーに失敗しました", checkingProvider: "このプロバイダーのすべてのキーを確認しています...", checkComplete: "確認完了: 利用可能 {valid}、無効 {invalid}、エラー {error}", checkFailed: "確認に失敗しました。ネットワークまたはプロバイダー設定を確認してください。", keyValid: "この API Key は利用可能です", keyInvalid: "この API Key は無効です", keyCheckError: "確認中にエラーが発生しました。後でもう一度お試しください。", keyReplaced: "API Key を置き換えました", remarkSaved: "メモを保存しました", keySaved: "API Key を保存しました", editSaveFailed: "変更を保存できませんでした", keySaveFailed: "API Key を保存できませんでした", keyDeleted: "API Key を削除しました", keyDeleteFailed: "API Key を削除できませんでした", openPlatformFailed: "プロバイダーの管理ページを開けませんでした", providerConfigured: "このプロバイダーは設定済みです", providerAdded: "プロバイダー設定を追加しました", providerExists: "同じ名前のプロバイダーが存在します", customProviderAdded: "カスタムプロバイダー設定を追加しました" },
  },
  providers: { title: "プロバイダー", description: "組み込みサービスとカスタム API エンドポイントを管理します。", addProvider: "プロバイダーを追加", builtin: "組み込みプロバイダー", custom: "カスタムプロバイダー", keyCount: "{count} 個のキー", deleteAction: "プロバイダーを削除", deleteAria: "{name} を削除", deleteDialog: { title: "プロバイダーを削除", withKeys: "「{name}」を削除しますか？このプロバイダーの {count} 個の API Key も削除されます。この操作は元に戻せません。", withoutKeys: "「{name}」を削除しますか？この操作は元に戻せません。" }, notices: { addFailed: "追加できませんでした：同じ名前のプロバイダーが存在します", added: "カスタムプロバイダーを追加し、ダッシュボードに反映しました", saveFailed: "保存できませんでした：名前が重複しているか、設定が無効です", saved: "プロバイダー設定を保存し、ダッシュボードに反映しました", deleted: "プロバイダー「{name}」を削除しました", deleteFailed: "プロバイダーを削除できませんでした" } },
  settings: { title: "設定", description: "言語、ローカルデータ、アプリ情報。", language: { title: "言語", description: "画面の表示言語を選択します。初期設定はシステムに従います。", label: "表示言語", system: "システム設定に従う", simplifiedChinese: "简体中文", traditionalChinese: "繁體中文", english: "English", japanese: "日本語" }, storage: { title: "ローカルストレージ", description: "プロバイダーとキーのメタデータはこのフォルダーに保存され、アプリ設定は settings.json に書き込まれます。", loading: "ローカルデータフォルダーを読み取っています", openFailed: "ローカルストレージを開けませんでした" }, logs: { title: "アプリログ", description: "ローカル操作と確認結果", loading: "ログフォルダーを読み取っています", clearLogs: "ログを消去", openDirectory: "フォルダーを開く", cleared: "ログを消去しました", clearFailed: "ログを消去できませんでした", openFailed: "ログフォルダーを開けませんでした", clearDialogTitle: "アプリログを消去", clearDialogMessage: "ローカルのアプリログをすべて消去しますか？この操作は元に戻せません。" }, version: { current: "現在のバージョン {version}", checkUpdates: "更新を確認", latest: "最新バージョンです", checkFailed: "更新を確認できませんでした。後でもう一度お試しください。", githubFailed: "GitHub リポジトリを開けませんでした", releaseFailed: "リリースのダウンロードページを開けませんでした" } },
  keyDialog: { unnamed: "名前のないキー", addTitle: "API Key を追加", editTitle: "API Key を編集", remark: "メモ", remarkPlaceholder: "例：開発環境", key: "API Key", newKey: "新しい API Key", keyPlaceholder: "API Key を貼り付け", saveKey: "キーを保存", saveChanges: "変更を保存", errors: { keyRequired: "API Key を入力してください", noChanges: "メモを変更するか、新しい API Key を入力してください" } },
  providerDialog: { configurationTitle: "設定を追加", configurationDescription: "組み込みプロバイダーを選択するか、カスタムプロバイダーを設定します。", configurationType: "設定の種類", builtinTab: "組み込み", customTab: "カスタム", configured: "設定済み", avatar: "プロバイダーのアバター", avatarHelp: "PNG、JPG、WebP、最大 2 MB", avatarHelpOptional: "任意。PNG、JPG、WebP、最大 2 MB。", name: "プロバイダー名", namePlaceholder: "例：社内モデルゲートウェイ / OneAPI", platformUrl: "管理 URL", addConfiguration: "設定を追加", addProvider: "プロバイダーを追加", customTitle: "カスタムプロバイダーを追加", customDescription: "プロバイダー名、エンドポイント、任意のアバターを設定します。", editTitle: "プロバイダー設定", editDescription: "プロバイダー名と管理 URL を変更します。", errors: { selectBuiltin: "組み込みプロバイダーを選択してください", nameRequired: "プロバイダー名を入力してください", platformUrlRequired: "管理 URL を入力してください", invalidUrl: "有効な HTTP または HTTPS URL を入力してください", invalidAvatarType: "アバターは PNG、JPG、WebP のいずれかにしてください", avatarTooLarge: "アバターは 2 MB 以下にしてください", avatarReadFailed: "アバターを読み取れませんでした。画像を選び直してください。" } },
  status: { valid: "利用可能", untested: "未確認", invalid: "無効", error: "確認エラー", checking: "確認中" },
  update: { stable: "安定版", available: "新しいバージョン v{version} があります", current: "現在のバージョン v{version}", view: "更新を表示", remindLater: "後で通知", later: "後で", downloadAndInstall: "今すぐ更新", downloading: "更新をダウンロード中", timeout: "ダウンロードがタイムアウトしました。ネットワークを確認して再試行してください。", failed: "更新のダウンロードに失敗しました。後でもう一度お試しください。" },
  errors: { desktopRequired: "ローカルデータ機能はデスクトップアプリで使用してください", dataDirectoryUnavailable: "アプリデータフォルダーを読み取れませんでした", logDirectoryUnavailable: "ログフォルダーを読み取れませんでした", directoryCreateFailed: "必要なフォルダーを作成できませんでした", directoryOpenFailed: "フォルダーを開けませんでした", dataReadFailed: "ローカルデータを読み取れませんでした", dataInvalid: "ローカルデータの形式が正しくありません", dataSaveFailed: "ローカルデータを保存できませんでした", keyringUnavailable: "システムの資格情報ストアを利用できません", keyringReadFailed: "システムの資格情報ストアから API Key を読み取れませんでした", keyringWriteFailed: "システムの資格情報ストアに書き込めませんでした", keyringDeleteFailed: "システムの資格情報ストアから API Key を削除できませんでした", networkClientFailed: "ネットワーク接続を初期化できませんでした", versionInvalid: "アプリのバージョン形式が正しくありません", updateCheckFailed: "更新サービスに接続できませんでした", updateResponseTooLarge: "更新サービスの応答が大きすぎます", updateDataInvalid: "更新情報の形式が正しくありません", updateTagInvalid: "更新バージョンタグが無効です", updateManifestFailed: "署名付き更新マニフェストを読み取れませんでした", updateDownloadTimeout: "更新のダウンロードがタイムアウトしました。ネットワークを確認して再試行してください。", updateDownloadFailed: "更新のダウンロードまたは署名の検証に失敗しました", updateInstallFailed: "更新をインストールできませんでした", updateNotAvailable: "このバージョンにはインストール可能な更新がありません", providerNameRequired: "プロバイダー名は必須です", providerExists: "プロバイダーはすでに存在します", providerNameExists: "同じ名前のプロバイダーが存在します", providerNotFound: "プロバイダーが見つかりません", providerOrderInvalid: "プロバイダーの並び順データが不完全です", apiKeyRequired: "API Key は必須です", apiKeyNotFound: "API Key が見つかりません", clipboardWriteFailed: "クリップボードに書き込めませんでした", settingsReadFailed: "アプリ設定を読み取れませんでした", settingsInvalid: "アプリ設定ファイルの形式が正しくありません", settingsSaveFailed: "アプリ設定を保存できませんでした", logUnavailable: "ログ機能を一時的に利用できません", logClearFailed: "ログを消去できませんでした", unknown: "操作に失敗しました。後でもう一度お試しください。" },
} satisfies MessageSchema;

export default jaJP;
