import type { MessageSchema } from "./zh-CN";

const zhTW = {
  common: { close: "關閉", cancel: "取消", save: "儲存", delete: "刪除", configure: "設定", open: "開啟", clear: "清除", optional: "選填", required: "必填", expand: "展開", collapse: "收合", uploadImage: "上傳圖片", replaceImage: "更換圖片", removeAvatar: "移除頭像", providerIconAlt: "{name} 圖示", selectedProviderAvatarAlt: "已選取的供應商頭像" },
  navigation: { main: "主要導覽", dashboard: "儀表板", providers: "供應商", settings: "設定" },
  dashboard: {
    title: "儀表板", searchPlaceholder: "搜尋供應商或 Key 備註", addConfiguration: "新增設定", statisticsLabel: "Key 統計", providerCount: "供應商數量", keyCount: "Key 總數", availableKeyCount: "可用 Key", dragToReorder: "按住拖曳以調整順序", officialProvider: "官方", customProvider: "自訂", noPlatformUrl: "尚未設定平台管理網址", availableSummary: "（{count} 可用）", refreshStatus: "重新檢查狀態", validationUnsupported: "此供應商尚未設定 Key 檢查", addKey: "新增 Key",
    columns: { remark: "備註", maskedKey: "API Key（部分隱藏）", status: "狀態", actions: "操作" },
    actions: { checkKey: "檢查 Key", editKey: "編輯 Key", copyKey: "複製 Key", copied: "已複製", deleteKey: "刪除 Key" },
    keyDisclosure: "僅顯示部分 Key；完整密鑰不會回傳到清單。",
    empty: { noMatchesTitle: "找不到相符的供應商或備註", noProvidersTitle: "尚未設定供應商", noMatchesDescription: "請嘗試其他搜尋關鍵字。", noProvidersDescription: "從內建供應商開始，或建立自訂供應商。", clearSearch: "清除搜尋" },
    deleteKeyDialog: { title: "刪除 API Key", message: "確定要刪除此 API Key 嗎？此操作無法復原。" },
    notices: { copied: "已複製到剪貼簿", copyFailed: "複製失敗", checkingProvider: "正在檢查此供應商下所有 Key 的狀態...", checkComplete: "檢查完成：{valid} 可用、{invalid} 無效、{error} 異常、{unsupported} 不支援", checkFailed: "檢查失敗，請確認網路或供應商設定", validationUnsupported: "請先設定檢查方式，再檢查此供應商", keyValid: "此 API Key 可用", keyInvalid: "此 API Key 無效", keyCheckError: "檢查發生異常，請稍後再試", keyReplaced: "API Key 已替換", remarkSaved: "備註已儲存", keySaved: "API Key 已儲存", editSaveFailed: "儲存變更失敗", keySaveFailed: "儲存 API Key 失敗", keyDeleted: "API Key 已刪除", keyDeleteFailed: "刪除 API Key 失敗", openPlatformFailed: "無法開啟此供應商的平台管理網址", providerConfigured: "此供應商已設定", providerAdded: "已新增供應商設定", providerExists: "供應商名稱已存在", customProviderAdded: "已新增自訂供應商設定" },
  },
  providers: { title: "供應商", description: "管理內建服務商與自訂 API 端點。", addProvider: "新增供應商", builtin: "內建供應商", custom: "自訂供應商", keyCount: "{count} 個 Key", deleteAction: "刪除供應商", deleteAria: "刪除 {name}", deleteDialog: { title: "刪除供應商", withKeys: "確定要刪除「{name}」嗎？此供應商的 {count} 個 API Key 也會一併刪除，此操作無法復原。", withoutKeys: "確定要刪除「{name}」嗎？此操作無法復原。" }, notices: { addFailed: "新增失敗：供應商名稱已存在", added: "已新增自訂供應商，首頁也已同步顯示", saveFailed: "儲存失敗：供應商名稱已存在或設定無效", saved: "供應商設定已儲存，首頁網址也已同步更新", deleted: "已刪除供應商「{name}」", deleteFailed: "刪除供應商失敗" } },
  settings: { title: "設定", description: "外觀、語言、本機資料與應用程式資訊。", language: { title: "語言", description: "選擇介面顯示語言。預設為跟隨系統。", label: "介面語言", system: "跟隨系統", simplifiedChinese: "简体中文", traditionalChinese: "繁體中文", english: "English", japanese: "日本語" }, appearance: { title: "外觀", description: "選擇介面的色彩主題。跟隨系統會自動回應系統外觀變化。", label: "色彩主題", system: "跟隨系統", light: "淺色", dark: "深色" }, storage: { title: "本機儲存", description: "供應商與 Key 中繼資料儲存在此目錄，應用程式設定寫入 settings.json。", loading: "正在讀取本機資料目錄", openFailed: "無法開啟本機儲存位置" }, logs: { title: "執行記錄", description: "本機操作與檢查結果", loading: "正在讀取記錄目錄", clearLogs: "清除記錄", openDirectory: "開啟目錄", cleared: "記錄已清除", clearFailed: "清除記錄失敗", openFailed: "無法開啟記錄目錄", clearDialogTitle: "清除執行記錄", clearDialogMessage: "確定要清除所有本機執行記錄嗎？此操作無法復原。" }, version: { current: "目前版本 {version}", checkUpdates: "檢查更新", latest: "目前已是最新版本", checkFailed: "檢查更新失敗，請稍後再試", githubFailed: "無法開啟 GitHub 儲存庫", releaseFailed: "無法開啟版本下載頁面" } },
  keyDialog: { unnamed: "未命名 Key", addTitle: "新增 API Key", editTitle: "編輯 API Key", remark: "備註", remarkPlaceholder: "例如：開發環境", key: "API Key", newKey: "新的 API Key", keyPlaceholder: "貼上 API Key", saveKey: "儲存 Key", saveChanges: "儲存變更", errors: { keyRequired: "請輸入 API Key", noChanges: "請修改備註或輸入新的 API Key" } },
  providerDialog: { configurationTitle: "新增設定", configurationDescription: "選擇內建供應商快速接入，或設定自訂供應商。", configurationType: "設定類型", builtinTab: "內建供應商", customTab: "自訂供應商", configured: "已設定", avatar: "供應商頭像", avatarHelp: "PNG、JPG、WebP，最大 2MB", avatarHelpOptional: "選填，支援 PNG、JPG、WebP，最大 2MB。", name: "供應商名稱", namePlaceholder: "例如：公司內部大型語言模型閘道 / OneAPI", platformUrl: "平台管理網址", addConfiguration: "新增設定", addProvider: "新增供應商", customTitle: "新增自訂供應商", customDescription: "設定供應商名稱、端點網址與選填頭像。", editTitle: "供應商設定", editDescription: "修改供應商名稱、平台管理網址與 Key 檢查方式。", validation: { title: "Key 檢查", mode: "檢查方式", none: "不檢查", openaiCompatible: "OpenAI 相容介面", bearer: "Bearer Token", apiKeyHeader: "API Key Header", baseUrl: "API 基礎網址", endpoint: "檢查端點", headerName: "Key 請求標頭名稱", noneHelp: "不會將 API Key 傳送到任何外部網址。", securityWarning: "檢查時，完整 API Key 將傳送到你設定的 HTTPS 網址。", hostWarning: "檢查時，完整 API Key 將傳送到 {host}。" }, errors: { selectBuiltin: "請選擇一個內建供應商", nameRequired: "請輸入供應商名稱", platformUrlRequired: "請輸入平台管理網址", invalidUrl: "請輸入有效的 http 或 https 網址", validationUrlRequired: "請輸入有效的檢查網址", validationHttpsRequired: "檢查網址必須使用 HTTPS", validationUrlUnsafe: "檢查網址不可包含憑據、查詢參數或本機網路位址", validationHeaderRequired: "請輸入 Key 請求標頭名稱", validationHeaderInvalid: "此請求標頭名稱無效或不受允許", invalidAvatarType: "頭像僅支援 PNG、JPG 或 WebP 圖片", avatarTooLarge: "頭像圖片不可超過 2MB", avatarReadFailed: "讀取頭像失敗，請重新選擇圖片" } },
  status: { valid: "可用", untested: "未檢查", invalid: "無效", unsupported: "不支援檢查", error: "檢查異常", checking: "檢查中" },
  statusReasons: { timeout: "檢查請求逾時", network: "無法連線檢查端點", rateLimited: "供應商限制了檢查請求", serverUnavailable: "供應商服務暫時無法使用", endpointInvalid: "檢查端點設定無效或發生重新導向", unexpectedStatus: "供應商回傳了無法辨識的狀態" },
  update: { stable: "穩定版", available: "發現新版本 v{version}", current: "目前版本 v{version}", view: "檢視更新", remindLater: "稍後提醒", later: "稍後", downloadAndInstall: "下載並安裝", downloading: "正在下載更新", timeout: "下載逾時，請檢查網路後再試", failed: "更新下載失敗，請稍後再試" },
  errors: { desktopRequired: "請在桌面應用程式中使用本機資料功能", dataDirectoryUnavailable: "無法讀取應用程式資料目錄", logDirectoryUnavailable: "無法讀取記錄目錄", directoryCreateFailed: "無法建立所需目錄", directoryOpenFailed: "無法開啟目錄", dataReadFailed: "無法讀取本機資料", dataInvalid: "本機資料格式錯誤", dataSaveFailed: "無法儲存本機資料", keyringUnavailable: "系統密鑰庫無法使用", keyringReadFailed: "無法從系統密鑰庫讀取 API Key", keyringWriteFailed: "無法寫入系統密鑰庫", keyringDeleteFailed: "無法從系統密鑰庫刪除 API Key", networkClientFailed: "無法初始化網路連線", versionInvalid: "應用程式版本格式無效", updateCheckFailed: "無法連線更新服務", updateResponseTooLarge: "更新服務回應過大", updateDataInvalid: "更新資訊格式錯誤", updateTagInvalid: "更新版本標籤無效", updateManifestFailed: "無法讀取簽章更新資訊清單", updateDownloadTimeout: "更新下載逾時，請檢查網路後再試", updateDownloadFailed: "更新下載或簽章驗證失敗", updateInstallFailed: "更新安裝失敗", updateNotAvailable: "此版本沒有可安裝的更新", providerNameRequired: "供應商名稱不可為空", providerExists: "供應商已存在", providerNameExists: "供應商名稱已存在", providerNotFound: "找不到供應商", providerOrderInvalid: "供應商排序資料不完整", providerValidationInvalid: "供應商 Key 檢查設定無效", apiKeyRequired: "API Key 不可為空", apiKeyNotFound: "找不到 API Key", clipboardWriteFailed: "無法寫入剪貼簿", settingsReadFailed: "無法讀取應用程式設定", settingsInvalid: "應用程式設定檔格式錯誤", settingsSaveFailed: "無法儲存應用程式設定", logUnavailable: "記錄功能暫時無法使用", logClearFailed: "無法清除記錄", unknown: "操作失敗，請稍後再試" },
} satisfies MessageSchema;

export default zhTW;
